{
 "title": "Updates",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2024-01-01T00:08:10.000Z" },
 "panels": [
  {
   "title": "Main",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "pragyan_table",
     "rawSql": "SELECT * FROM pragyan_table.`match update` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max No. of Single event (Goals)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pragyan_table",
     "rawSql": "SELECT COUNT(`Event ID.1`) FROM pragyan_table.`match update` GROUP BY `Event Type` ORDER BY COUNT(`Event ID.1`) ASC LIMIT 540 "
    }
   ]
  },
  {
   "title": "Events Occuring",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "pragyan_table",
     "rawSql": "SELECT Timestamp, `Event ID.1` FROM pragyan_table.`match update` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Legend",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "dataset": "pragyan_table",
     "rawSql": "SELECT `Event Type`, MIN(`Event ID.1`) FROM pragyan_table.`match update` GROUP BY `Event Type` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Status Bar",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "pragyan_table",
     "rawSql": "SELECT `Event Type`, COUNT(`Event Type`) FROM pragyan_table.`match update` GROUP BY `Event Type` LIMIT 50 "
    }
   ]
  },
  {
   "title": "Comparisons",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "dataset": "pragyan_table",
     "rawSql": "SELECT `Event Type`, COUNT(`Event Type`) FROM pragyan_table.`match update` GROUP BY `Event Type` LIMIT 50 "
    }
   ]
  }
 ]
}